CREATE TABLE "products_inventory" (
	"id" serial PRIMARY KEY NOT NULL,
	"category" text,
	"sku" text,
	"woo_id" integer,
	"shape" text,
	"weight" numeric,
	"color" text,
	"clarity" text,
	"lab" text,
	"fluorescence" text,
	"price_per_carat" numeric,
	"rap_price_percent" numeric,
	"rap_price" numeric,
	"total_price" numeric,
	"location" text,
	"image" text,
	"video" text,
	"certificate_image" text,
	"certificate_number" text,
	"cut" text,
	"polish" text,
	"symmetry" text,
	"table" numeric,
	"depth" numeric,
	"ratio" numeric,
	"measurements" text,
	"pair_stone" text,
	"fancy_intensity" text,
	"fancy_color" text,
	"fancy_overtone" text,
	"fancy_color_2" text,
	"fancy_overtone_2" text,
	"home_page" text,
	"additional_pictures" text,
	"branch" text,
	"additional_videos" text,
	"comment" text,
	"type" text,
	"cert_comments" text,
	"certificate_image_jpg" text,
	"origin" text,
	"trade_show" text,
	"status" varchar(255),
	"uploaded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "products_raw" (
	"id" serial PRIMARY KEY NOT NULL,
	"category" text,
	"sku" text,
	"shape" text,
	"weight" numeric,
	"color" text,
	"clarity" text,
	"lab" text,
	"fluorescence" text,
	"price_per_carat" numeric,
	"rap_price_percent" numeric,
	"rap_price" numeric,
	"total_price" numeric,
	"location" text,
	"image" text,
	"video" text,
	"certificate_image" text,
	"certificate_number" text,
	"cut" text,
	"polish" text,
	"symmetry" text,
	"table" numeric,
	"depth" numeric,
	"ratio" numeric,
	"measurements" text,
	"pair_stone" text,
	"fancy_intensity" text,
	"fancy_color" text,
	"fancy_overtone" text,
	"fancy_color_2" text,
	"fancy_overtone_2" text,
	"home_page" text,
	"additional_pictures" text,
	"branch" text,
	"additional_videos" text,
	"comment" text,
	"type" text,
	"cert_comments" text,
	"certificate_image_jpg" text,
	"origin" text,
	"trade_show" text,
	"uploaded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "upload_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"inserted_rows" integer NOT NULL,
	"status" text,
	"uploaded_at" timestamp DEFAULT now()
);
